### ISSUE TITLE
[FE] Discussion UI 구현 

### ISSUE THREAD

**Issue by greenblues1190** [woowacourse-teams/2022-moragora#15]
## 요구사항
- [x] 폰트 import
  - 영어 폰트
  - 한글 폰트 [Noto Sans KR](https://fonts.google.com/noto/specimen/Noto+Sans+KR)
- [x] HTML 마크업
- [x] 전역 스타일
  - [reset](https://meyerweb.com/eric/tools/css/reset/)
  - global
    - `box-sizing`
- [ ] 테마
  - colors
  - media
- [ ] 컴포넌트
  - [x] Header
  - [x] Footer
  - [x] Content
  - [x] Logo
  - [x] Button
  - [ ] Label
  - [ ] Input
  - [ ] Textarea
  - [ ] DivideLine
  - [ ] ModelWindow
  - [ ] Form
  - [x] Discussion
  - [ ] Avatar

- [ ] 페이지
  - [x] DiscussionListPage
  - [x] DiscussionPostPage
  - [x] DiscussionDetailPage
  - [ ] DiscussionEditPage

## 기한
22.07.05

**Comment by kamwoo** [comment]
ㅎㅇ

**Comment by kamwoo** [comment]
1. 컴포넌트 분리
2. routing, react-router-dom
3. msw
4. 비동기
