### ISSUE TITLE
[FE] E2E 테스트 코드 작성

### ISSUE THREAD

**Issue by kamwoo** [woowacourse-teams/2022-moragora#262]

**Comment by greenblues1190** [comment]
## Jenkins에서 Cypress로 E2E 테스트 설정

### 리눅스 Headless 브라우저 설정

Cypress에서 제공해주는 리눅스용 docker image가 있지만 현재 Jenkins에서 docker를 사용하고 있지 않기 때문에 Cypress에 내장된 Electron browser 사용. 다른 브라우저을 Headless 버전으로 리눅스에 설치하는 방법도 있지만 어려움.

### Jenkins에게 테스트 결과 전달

리포터를 사용해 xml이나 json 형태로 출력. 이번 스프린트에서는 [mocha-junit-reporter](https://github.com/michaelleeallen/mocha-junit-reporter) 라이브러리를 사용하여 xml 파일로 출력하였음. 출력된 파일에서 [xmllint](https://gnome.pages.gitlab.gnome.org/libxml2/xmllint.html)와 쉘 스크립트를 사용해 실패 테스트 수를 파싱하여 0이 아니라면 exit code 1을 발생시키고 종료.
  
### 최종 Jenkins 빌드 스크립트

```bash
#!/bin/bash
cd /var/lib/jenkins/workspace/moragora-frontend-build-on-pull-request/frontend/
echo "API_SERVER_HOST=insert_your_api_server_url_here" > .env
npm install
npm run test:ci

testResult=$(xmllint --xpath /testsuites/@failures test-result.xml | perl -ne 'print "$1\n" if /failures="(.*?)"/')
if [ $testResult = "0" ]
then
  echo "test result: successed"
else
  echo "test result: failed"
  exit 1
fi

npm run build
```
