### ISSUE TITLE
[BE] Filter를 통해 Logging 처리하도록 변경  

### ISSUE THREAD

**Issue by syoun602** [woowacourse-teams/2022-moragora#415]
## 요구사항
- 기존에 AOP로 동작하던 logging 방식을 Filter를 통한 logging 방식으로 변경한다.
- 민감한 정보는 log에서 제외한다.

**Comment by syoun602** [comment]
1. Email은 masking 하지 않기
2. access token은 masking 하기.
3. access token은 존재하지 않으면 아예 header 안보이게 하기
4. password 길이가 일정하도록 변경하기
5. 머지 전에 local에서 로그 파일 찍지 않게 변경하기
6. SQL 찍어야 함

### 논의사항
1. prod에서 error/info가 한번에 보이는 건 어떨까? 에 대한 논의
2. local에서 DEBUG를 쓸까 말까?

**Comment by progress0407** [comment]
https://github.com/woowacourse-teams/2022-moragora/issues/415#issuecomment-1247511285

+ 7. `LoggingFilter` 에 `static` 지우기
