### ISSUE TITLE
[FE] webpack output filename에 hash 추가를 통한 Cache Busting

### ISSUE THREAD

**Issue by kamwoo** [woowacourse-teams/2022-moragora#432]
## 요구사항
- webpack output filename에 content-hash 추가
  -  `output.filename`에 `[contenthash]`를 추가한다.
  - `output.assetModuleFilename`의 `[hash]`를 `[contenthash]`로 변경한다. 

## 기한
2022.09.16

**Comment by kamwoo** [comment]
## Webpack hash template string
cache busting을 위해서 ouput filename에 hash 값을 추가합니다.
컴파일 수준에서 사용하는 `fullhash`를 제외한 보편적으로 사용하는 `hash`, `contenthash`, `chunkhash` 중에서 선택했습니다.

hash | contenthash | chunkhash
----- | ------------ | -----------|
<image height=300 src=https://user-images.githubusercontent.com/61308364/190638873-a88a5e7f-5666-45c8-a917-5bf58cb60631.png  /> | <image height=300 src=https://user-images.githubusercontent.com/61308364/190639439-19ea8f9e-a4b7-4eb0-80d4-e49f9cbca2b3.png /> |  <image height=300 src=https://user-images.githubusercontent.com/61308364/190639041-299f6e51-f4d2-4776-9233-fa4078df4320.png /> |
빌드 시점에 전체 코드를 기준으로 생성되고, 모든 hash 값은 동일하다. | 파일의 content에 따라서 hash값이 생성된다. | chunk 파일의 content를 기준으로 hash값이 생성된다. 같은 chunk 내에서 hash값을 공유한다. 

**공통: 내용의 변경이 발생했을 때 hash값이 변경된다.**

### asset/resource file에서 hash 적용 방식
>You are getting a new hash per image file, because with [asset/resource](https://webpack.js.org/guides/asset-modules/) you asked Webpack to emit resources to separate files. When you use [hash] placeholder, Webpack would generate a hash out of the filename. Since you have different filenames -> different hashes.

-> asset/resource로 Webpack에 리소스를 별도의 파일을 내보내도록 요청 했기 때문에 이미지 파일당 새로운 해시를 얻게 됩니다 .
`[hash]` placeholder를 사용하면 Webpack은 파일 이름에서 해시를 생성합니다. 파일 이름이 다르므로 해시가 다릅니다.

---
### 결론
webpack `output.filename`을 `contenthash`로 설정함으로써 변경되지 않은 파일에 대해서는 filename을 변경하지않고 그에 따라서 busting하지 않기 때문에 caching을 유지하도록 합니다. `hash`나 `contenthash` template string 영향을 받지 않으므로 webpack docs를 따라서 `hash`로 설정했습니다.

**Comment by greenblues1190** [comment]
## `asset/resource`의 filename 해시 옵션

> 파일을 출력 디렉터리로 내보낼 때 asset/resource 모듈은 기본적으로 [hash][ext][query] 파일명을 사용합니다.'
> webpack 설정에서 [output.assetModuleFilename](https://webpack.kr/configuration/output/#outputassetmodulefilename)을 설정하여 이 템플릿을 수정할 수 있습니다.

```javascript
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
    assetModuleFilename: 'images/[hash][ext][query]'
  },
  module: {
    rules: [
      {
        test: /\.png/,
        type: 'asset/resource'
      }
    ]
  },
};
```

https://webpack.kr/guides/asset-modules/#custom-output-filename
